routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');


//Auth::routes();

/* Login Routes */
Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('/login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
Route::get('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
Route::post('/logout', ['as' => 'logout.post', 'uses' => 'Auth\LoginController@logout']);

/* Registration Routes */
Route::get('/register', ['as' => 'register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
Route::post('/register', ['as' => 'register.post', 'uses' => 'Auth\RegisterController@register']);

/* Forgot Password Routes */
//Route::get('/password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
//Route::post('/password/email', ['as' => 'password.email.post', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
//Route::get('/password/reset/{token}', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
//Route::post('/password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);

Route::group([
    "prefix" => 'admin'
], function () {

    Route::get('/', function () {
        return redirect('/admin/users');
    });

    /* users */
    Route::get('/users/draw',
        ['as' => 'admin.users.draw',
            'uses' => '\App\Http\Controllers\UserController@draw']
    );

    Route::resource('/users', 'UserController', [
        'as' => 'admin'
    ]);

    Route::delete('/users/{id}/delete',
        ['as' => 'admin.users.delete',
            'uses' => '\App\Http\Controllers\UserController@destroy']
    );

    Route::post('/users/delete-selected',
        ['as' => 'admin.users.delete-selected',
            'uses' => '\App\Http\Controllers\UserController@destroySelected']
    );
    /* users */

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'address',
        'post_code',
        'contact_number',
        'email',
        'user_name',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($value)
    {
        if($value != ""){
            $this->attributes['password'] = bcrypt($value);
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\UserRepository;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @param User $user_model
     * @param UserRepository $user_repository
     *
     * @return void
     */
    public function __construct(User $user_model, UserRepository $user_repository)
    {
        $this->middleware('auth', ['except' => ['index']]);

        /*
        * Model namespace
        * using $this->user_model can also access $this->user_model->where('id', 1)->get();
        * */
        $this->user_model = $user_model;

        /*
        * Repository namespace
        * this class may include methods that can be used by other controllers, like getting of posts with other data (related tables).
         * */
        $this->user_repository = $user_repository;
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        if (auth()->check()) {
            $users = $this->user_model->get();
            return view('pages.user.index', compact('users'));
        } else {
            return view('home');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = $this->user_repository->getById($id);

        return view('pages.user.show', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $response = [
            'status' => false,
            'messages' => [
                'swal' => [
                    'icon' => 'error',
                    'title' => 'Error!',
                    'text' => 'Something went wrong!',
                ]
            ],
            'data' => [],
        ];

        $this->validate($request, [
            'first_name' => ['required', 'string', 'max:255'],
            'last_name' => ['required', 'string', 'max:255'],
            'address' => ['required', 'string', 'max:255'],
            'post_code' => ['required', 'string', 'max:255'],
            'contact_number' => ['required', 'string', 'max:255'],
            'user_name' => ['required', 'string', 'max:255', 'unique:users,user_name,NULL,id,deleted_at,NULL'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email,NULL,id,deleted_at,NULL'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        $user = $this->user_model->create([
            'first_name' => $request['first_name'],
            'last_name' => $request['last_name'],
            'address' => $request['address'],
            'post_code' => $request['post_code'],
            'contact_number' => $request['contact_number'],
            'user_name' => $request['user_name'],
            'email' => $request['email'],
            'password' => bcrypt($request['password']),
        ]);

        $response['status'] = true;
        $response['messages']['swal'] = [
            'icon' => 'success',
            'title' => 'Success!',
            'text' => 'User successfully added.',
            'redirect_route' => route('admin.users.index')
        ];
        $response['data'] = $user;

        return json_encode($response);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->user_repository->getById($id);

        return view('pages.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $response = [
            'status' => false,
            'messages' => [
                'swal' => [
                    'icon' => 'error',
                    'title' => 'Error!',
                    'text' => 'Something went wrong!',
                ]
            ],
            'data' => [],
        ];

        $user = $this->user_repository->getById($id);

        $this->validate($request, [
            'first_name' => ['required', 'string', 'max:255'],
            'last_name' => ['required', 'string', 'max:255'],
            'address' => ['required', 'string', 'max:255'],
            'post_code' => ['required', 'string', 'max:255'],
            'contact_number' => ['required', 'string', 'max:255'],
            'user_name' => ['required', 'string', 'max:255', 'unique:users,user_name,' . $id . ',id,deleted_at,NULL'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email,' . $id . ',id,deleted_at,NULL'],
            'password' => 'exclude_if:change_password,false|string|min:8|confirmed',
        ]);

        if ($request->get('change_password')) {
            $input = $request->except(['change_password']);
        } else {
            $input = $request->except(['change_password', 'password']);
        }

        $user->fill($input)->save();

        $response['status'] = true;
        $response['messages']['swal'] = [
            'icon' => 'success',
            'title' => 'Success!',
            'text' => 'User successfully updated.',
            'redirect_route' => route('admin.users.index')
        ];
        $response['data'] = $user;

        return json_encode($response);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = $this->user_repository->getById($id);

        $user->delete();

        $response['status'] = true;
        $response['messages']['swal'] = [
            'icon' => 'success',
            'title' => 'Success!',
            'text' => 'User successfully deleted.',
            'redirect_route' => route('admin.users.index')
        ];
        $response['data'] = [];

        return json_encode($response);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function destroySelected(Request $request)
    {
        $users = $this->user_model->whereIn('id', $request->get('ids'))->get()->each(function ($user, $key) {
            $user->delete();
        });

        $response['status'] = true;
        $response['messages']['swal'] = [
            'icon' => 'success',
            'title' => 'Success!',
            'text' => 'User(s) successfully deleted.',
            'redirect_route' => route('admin.users.index')
        ];
        $response['data'] = [];

        return json_encode($response);
    }

    /**
     * Datatables draw
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function draw(Request $request)
    {
        $columns = array(
            0 => 'checkbox',
            1 => 'id',
            2 => 'name',
            3 => 'user_name',
            4 => 'email',
            54 => 'action',
        );

        $totalData = $this->user_model
            ->select('users.*', (DB::raw("CONCAT(`users`.`first_name`, ' ', `users`.`last_name`) as name")))
            ->count();

        $totalFiltered = $totalData;
        $limit = $request->input('length');
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir = $request->input('order.0.dir');

        if (empty($request->input('search.value'))) {
            if ($limit == -1) {
                $users = $this->user_model
                    ->select('users.*', (DB::raw("CONCAT(`users`.`first_name`, ' ', `users`.`last_name`) as name")))
                    ->orderBy($order, $dir)
                    ->get();
            } else {
                $users = $this->user_model
                    ->select('users.*', (DB::raw("CONCAT(`users`.`first_name`, ' ', `users`.`last_name`) as name")))
                    ->offset($start)
                    ->limit($limit)
                    ->orderBy($order, $dir)
                    ->get();
            }
        } else {
            $search = $request->input('search.value');

            if ($limit == -1) {
                $users = $this->user_model
                    ->orWhere('user_name', 'LIKE', "%{$search}%")
                    ->orWhere('email', 'LIKE', "%{$search}%")
                    ->orWhere((DB::raw("CONCAT(`users`.`first_name`, ' ', `users`.`last_name`)")), 'LIKE', "%{$search}%")
                    ->select('users.*', (DB::raw("CONCAT(`users`.`first_name`, ' ', `users`.`last_name`) as name")))
                    ->orderBy($order, $dir)
                    ->get();
            } else {
                $users = $this->user_model
                    ->orWhere('user_name', 'LIKE', "%{$search}%")
                    ->orWhere('email', 'LIKE', "%{$search}%")
                    ->orWhere((DB::raw("CONCAT(`users`.`first_name`, ' ', `users`.`last_name`)")), 'LIKE', "%{$search}%")
                    ->select('users.*', (DB::raw("CONCAT(`users`.`first_name`, ' ', `users`.`last_name`) as name")))
                    ->offset($start)
                    ->limit($limit)
                    ->orderBy($order, $dir)

resources/views/pages/user/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">Users</a></li>
                <li class="breadcrumb-item active"
                    aria-current="page">Add New User</li>
            </ol>
        </nav>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <user-create></user-create>
                        <!--
                        {{  Form::open([
                            'method' => 'POST',
                            'id' => 'create-user',
                            'route' => ['admin.users.store'],
                            'class' => 'form-horizontal '
                            ])
                        }}
                        <div class="form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
                            <label class="col-md-3 control-label" for="first_name">Firstname</label>

                            <div class="col-md-9">
                                <input type="text" class="form-control" id="first_name" name="first_name"
                                       value="{{ old('first_name') }}"
                                       placeholder="Enter firstname..">
                                @if($errors->has('first_name'))
                                    <span class="help-block animation-slideDown">{{ $errors->first('first_name') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
                            <label class="col-md-3 control-label" for="last_name">Lastname</label>

                            <div class="col-md-9">
                                <input type="text" class="form-control" id="last_name" name="last_name"
                                       value="{{ old('last_name') }}"
                                       placeholder="Enter lastname..">
                                @if($errors->has('last_name'))
                                    <span class="help-block animation-slideDown">{{ $errors->first('last_name') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('user_name') ? ' has-error' : '' }}">
                            <label class="col-md-3 control-label" for="user_name">Username</label>

                            <div class="col-md-9">
                                <input type="text" class="form-control" id="user_name" name="user_name"
                                       value="{{ old('user_name') }}"
                                       placeholder="Enter username..">
                                @if($errors->has('user_name'))
                                    <span class="help-block animation-slideDown">{{ $errors->first('user_name') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label class="col-md-3 control-label" for="email">Email</label>

                            <div class="col-md-9">
                                <input type="text" class="form-control" id="email" name="email"
                                       value="{{ old('email') }}"
                                       placeholder="Enter email..">
                                @if($errors->has('email'))
                                    <span class="help-block animation-slideDown">{{ $errors->first('email') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label class="col-md-3 control-label" for="password">Password</label>

                            <div class="col-md-9">
                                <input type="password" class="form-control" id="password" name="password"
                                       placeholder="Enter password..">
                                @if($errors->has('password'))
                                    <span class="help-block animation-slideDown">{{ $errors->first('password') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                            <label class="col-md-3 control-label" for="password_confirmation">Password
                                Confirmation</label>

                            <div class="col-md-9">
                                <input type="password" class="form-control" id="password_confirmation"
                                       name="password_confirmation"
                                       placeholder="Verify Password..">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Is Active?</label>

                            <div class="col-md-9">
                                <label class="switch switch-primary">
                                    <input type="checkbox" id="is_active" name="is_active"
                                           value="1" checked>
                                    <span></span>
                                </label>
                            </div>
                        </div>
                        <div class="form-group form-actions">
                            <div class="col-md-9 col-md-offset-3">
                                <a href="{{ route('admin.users.index') }}" class="btn btn-sm btn-warning">Cancel</a>
                                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-floppy-o"></i> Save
                                </button>
                            </div>
                        </div>
                        {{ Form::close() }}
                        -->
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header clearfix">
                        <h2 class="float-left"><i class="fa fa-users"></i>&nbsp;<strong>Users</strong></h2>
                        <a href="{{ route('admin.users.create') }}" class="btn btn-success float-right">
                            <i class="fa fa-plus"></i> Add New User
                        </a>
                    </div>
                    <div class="card-body">
                        <div class="col-md-12">
                            <div class="alert alert-info alert-dismissable user-empty {{$users->count() == 0 ? '' : 'd-none' }}">
                                <i class="fa fa-info-circle"></i> No users found.
                            </div>
                            <user-list :users="{{ $users }}" :user="{{ auth()->user() }}"></user-list>
                            <!--
                            <div class="table-responsive {{$users->count() == 0 ? 'd-none' : '' }}">
                                <table id="users-table"
                                       class="table table-bordered table-striped table-vcenter">
                                    <thead>
                                    <tr role="row">
                                        <th class="text-left">
                                            Name
                                        </th>
                                        <th class="text-left">
                                            Username
                                        </th>
                                        <th class="text-left">
                                            Email
                                        </th>
                                        <th class="text-center">
                                            Action
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($users as $user)
                                        <tr data-user-template-id="{{$user->id}}">
                                            <td class="text-left">
                                                <strong>{{ $user->first_name.' '.$user->last_name }}</strong></td>
                                            <td class="text-left">{{ $user->user_name    }}</td>
                                            <td class="text-left">{{ $user->email }}</td>
                                            <td class="text-center">
                                                <div class="btn-group btn-group-sm" role="group">
                                                    <a href="{{ route('admin.users.show', $user->id) }}"
                                                       data-toggle="tooltip"
                                                       title=""
                                                       class="btn btn-default"
                                                       data-original-title="View"><i class="fa fa-eye"></i></a>
                                                    <a href="{{ route('admin.users.edit', $user->id) }}"
                                                       data-toggle="tooltip"
                                                       title=""
                                                       class="btn btn-default"
                                                       data-original-title="Edit"><i class="fa fa-edit"></i></a>
                                                    <a href="javascript:void(0)" data-toggle="tooltip"
                                                       title=""
                                                       class="btn btn-xs btn-danger delete-user-btn"
                                                       data-original-title="Delete"
                                                       data-user-id="{{ $user->id }}"
                                                       data-user-route="{{ route('admin.users.delete', $user->id) }}">
                                                        <i class="fa fa-times"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/user/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">Users</a></li>
                <li class="breadcrumb-item active"
                    aria-current="page">{{ $user->first_name . ' ' . $user->last_name }}</li>
            </ol>
        </nav>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header clearfix">
                        <a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-default float-right">
                            <i class="fa fa-edit"></i> Edit User
                        </a>
                    </div>
                    <div class="card-body">
                        <div class="block-section text-center">
                            <h3>
                                <strong>{{ $user->first_name.' '.$user->last_name }}</strong><br>
                                <small></small>
                            </h3>
                        </div>
                        <table class="table table-borderless table-striped table-vcenter">
                            <tbody>
                            <tr>
                                <td class="text-right"><strong>Username</strong></td>
                                <td>{{ $user->user_name }}</td>
                            </tr>
                            <tr>
                                <td class="text-right"><strong>Email</strong></td>
                                <td>{{ $user->email }}</td>
                            </tr>
                            <tr>
                                <td class="text-right"><strong>Address</strong></td>
                                <td>{!! $user->address !!}</td>
                            </tr>
                            <tr>
                                <td class="text-right"><strong>Postcode</strong></td>
                                <td>{{ $user->post_code }}</td>
                            </tr>
                            <tr>
                                <td class="text-right"><strong>Contact Number</strong></td>
                                <td>{{ $user->contact_number }}</td>
                            </tr>
                            <tr>
                                <td class="text-right"><strong>Creation Date</strong></td>
                                <td>{{ $user->created_at->format('F d, Y h:i:s a') }}</td>
                            </tr>
                            <tr>
                                <td class="text-right"><strong>Last Visit</strong></td>
                                <td>{{ date('F d, Y h:i:s a', strtotime($user->last_login)) }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection