routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');


//Auth::routes();

/* Login Routes */
Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('/login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
Route::get('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
Route::post('/logout', ['as' => 'logout.post', 'uses' => 'Auth\LoginController@logout']);

/* Registration Routes */
Route::get('/register', ['as' => 'register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
Route::post('/register', ['as' => 'register.post', 'uses' => 'Auth\RegisterController@register']);

/* Forgot Password Routes */
//Route::get('/password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
//Route::post('/password/email', ['as' => 'password.email.post', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
//Route::get('/password/reset/{token}', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
//Route::post('/password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);

Route::group([
    "prefix" => 'admin'
], function () {

    Route::get('/', function () {
        return redirect('/admin/users');
    });

    /* users */
    Route::get('/users/draw',
        ['as' => 'admin.users.draw',
            'uses' => '\App\Http\Controllers\UserController@draw']
    );

    Route::resource('/users', 'UserController', [
        'as' => 'admin'
    ]);

    Route::delete('/users/{id}/delete',
        ['as' => 'admin.users.delete',
            'uses' => '\App\Http\Controllers\UserController@destroy']
    );

    Route::post('/users/delete-selected',
        ['as' => 'admin.users.delete-selected',
            'uses' => '\App\Http\Controllers\UserController@destroySelected']
    );
    /* users */

});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
@include('layouts.header')
<body>
<div id="app">
    @include('layouts.nav')
    <main class="">
        @yield('content')
    </main>
</div>

@include('layouts.footer')

</body>
</html>

resources/views/layouts/footer.blade.php
<!-- Site footer -->
<footer class="site-footer">
        <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p class="copyright-text">Copyright &copy; {{ date('Y') }} All Rights Reserved by
                    <a target="_blank" href="https://www.linkedin.com/in/randall-anthony-bondoc-aa95b9139/">Randall Anthony Bondoc</a>.
                </p>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
                <ul class="social-icons">
                    <li><a class="google" target="_blank" href="mailto:randallbondoc@gmail.com"><i class="fab fa-google"></i></a></li>
                    <li><a class="linkedin" target="_blank" href="https://www.linkedin.com/in/randall-anthony-bondoc-aa95b9139/"><i class="fab fa-linkedin"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/header.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-dark shadow-sm fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            <img src="{{ asset('images/logo-917V.svg') }}" width="50" height="50" class="d-inline-block align-top"
                 alt="">
            {{--{{ config('app.name', 'Laravel') }}--}}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                @auth
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.users.index') }}">{{ __('Users') }}</a>
                    </li>
                @endauth
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->first_name . ' ' . Auth::user()->last_name }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>